### ISSUE TITLE
Interactive tippy shows a weird internal border on hover for half a second

### ISSUE THREAD

**Issue by alicerocheman** [atomiks/tippyjs-react#318]
Interactive tippy shows a weird internal border on hover for half a second:
https://user-images.githubusercontent.com/21168856/124082323-e0463800-da4c-11eb-9192-6beb82671e95.mov

temp fixed with:
```css
.tippy-content {
  transition-property: none!important;
}
```
